project:
  name: quickstart-microsoft-sql-fci-fsx
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  s3_bucket: ''
tests:
  mssql-ec2ad:
    parameters:
      ADScenarioType: 'Microsoft AD on Amazon EC2'
      AvailabilityZones: $[taskcat_getaz_2]
      DomainAdminPassword: $[taskcat_genpass_16]
      EnableAppInsights: 'true'
      KeyPairName: $[taskcat_getkeypair]
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      NumberOfRDGWHosts: '0'
      RDGWCIDR: 0.0.0.0/0
      SQLServiceAccountPassword: $[taskcat_genpass_16]
      MSSQLMediaBucketName: override
      MSSQLMediaPathKey: SQLServer2019-x64-ENU.iso
    regions:
    - us-east-1
    s3_bucket: ''
    template: templates/mssqlfsx-main.template.yaml
  mssql-mad:
    parameters:
      ADScenarioType: 'AWS Directory Service for Microsoft AD (Enterprise Edition)'
      AvailabilityZones: $[taskcat_getaz_2]
      DomainAdminPassword: $[taskcat_genpass_16]
      EnableAppInsights: 'true'
      KeyPairName: $[taskcat_getkeypair]
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      NumberOfRDGWHosts: '0'
      RDGWCIDR: 0.0.0.0/0
      SQLServiceAccountPassword: $[taskcat_genpass_16]
      MSSQLMediaBucketName: override
      MSSQLMediaPathKey: SQLServer2019-x64-ENU.iso
    regions:
    - us-east-2
    s3_bucket: ''
    template: templates/mssqlfsx-main.template.yaml